=== smirnoal/crema-lambda-runtime/events-schemas/src/main/resources/schemas/apigw-rest-response.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "ApiGatewayProxyResponseEvent",
  "type": "object",
  "properties": {
    "statusCode": {
      "type": "integer"
    },
    "headers": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "multiValueHeaders": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "body": {
      "type": "string"
    },
    "isBase64Encoded": {
      "type": "boolean"
    }
  },
  "required": [ "statusCode" ],
  "additionalProperties": false
}

=== smirnoal/crema-lambda-runtime/events-schemas/src/test/resources/events/apigw-v2-websocket-response-sample.json
{
  "statusCode": 200,
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Encoding": "gzip, deflate, lzma, sdch, br",
    "Accept-Language": "en-US,en;q=0.8",
    "CloudFront-Forwarded-Proto": "https",
    "CloudFront-Is-Desktop-Viewer": "true",
    "CloudFront-Is-Mobile-Viewer": "false",
    "CloudFront-Is-SmartTV-Viewer": "false",
    "CloudFront-Is-Tablet-Viewer": "false",
    "CloudFront-Viewer-Country": "US",
    "Host": "wt6mne2s9k.execute-api.us-west-2.amazonaws.com",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36 OPR/39.0.2256.48",
    "Via": "1.1 fb7cca60f0ecd82ce07790c9c5eef16c.cloudfront.net (CloudFront)",
    "X-Amz-Cf-Id": "nBsWBOrSHMgnaROZJK1wGCZ9PcRcSpq_oSXZNQwQ10OTZL4cimZo3g==",
    "X-Forwarded-For": "192.168.100.1, 192.168.1.1",
    "X-Forwarded-Port": "443",
    "X-Forwarded-Proto": "https"
  },
  "multiValueHeaders": {
    "Accept": [ "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" ],
    "Accept-Encoding": [ "gzip, deflate, lzma, sdch, br" ],
    "Accept-Language": [ "en-US,en;q=0.8" ],
    "CloudFront-Forwarded-Proto": [ "https" ],
    "CloudFront-Is-Desktop-Viewer": [ "true" ],
    "CloudFront-Is-Mobile-Viewer": [ "false" ],
    "CloudFront-Is-SmartTV-Viewer": [ "false" ],
    "CloudFront-Is-Tablet-Viewer": [ "false" ],
    "CloudFront-Viewer-Country": [ "US" ],
    "Host": [ "wt6mne2s9k.execute-api.us-west-2.amazonaws.com" ],
    "Upgrade-Insecure-Requests": [ "1" ],
    "User-Agent": [ "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36 OPR/39.0.2256.48" ],
    "Via": [ "1.1 fb7cca60f0ecd82ce07790c9c5eef16c.cloudfront.net (CloudFront)" ],
    "X-Amz-Cf-Id": [ "nBsWBOrSHMgnaROZJK1wGCZ9PcRcSpq_oSXZNQwQ10OTZL4cimZo3g==" ],
    "X-Forwarded-For": [ "192.168.100.1, 192.168.1.1" ],
    "X-Forwarded-Port": [ "443" ],
    "X-Forwarded-Proto": [ "https" ]
  },
  "isBase64Encoded": false,
  "body": "Hello World"
}
