=== smirnoal/crema-lambda-runtime/events-schemas/src/main/resources/schemas/apigw-rest-request.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "ApiGatewayProxyRequestEvent",
  "type": "object",
  "properties": {
    "version": {
      "type": "string"
    },
    "resource": {
      "type": "string"
    },
    "path": {
      "type": "string"
    },
    "httpMethod": {
      "type": "string"
    },
    "headers": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "multiValueHeaders": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "queryStringParameters": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "multiValueQueryStringParameters": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "pathParameters": {
      "type": [ "object", "null" ],
      "additionalProperties": {
        "type": "string"
      }
    },
    "stageVariables": {
      "type": [ "object", "null" ],
      "additionalProperties": {
        "type": "string"
      }
    },
    "requestContext": {
      "$ref": "#/definitions/ProxyRequestContext"
    },
    "body": {
      "type": "string"
    },
    "isBase64Encoded": {
      "type": "boolean"
    }
  },
  "required": [ "path", "httpMethod" ],
  "additionalProperties": false,
  "definitions": {
    "ProxyRequestContext": {
      "type": "object",
      "properties": {
        "accountId": {
          "type": "string"
        },
        "stage": {
          "type": "string"
        },
        "resourceId": {
          "type": "string"
        },
        "requestId": {
          "type": "string"
        },
        "operationName": {
          "type": "string"
        },
        "identity": {
          "$ref": "#/definitions/RequestIdentity"
        },
        "resourcePath": {
          "type": "string"
        },
        "httpMethod": {
          "type": "string"
        },
        "apiId": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "authorizer": {
          "type": "object"
        },
        "extendedRequestId": {
          "type": "string"
        },
        "requestTime": {
          "type": "string"
        },
        "requestTimeEpoch": {
          "type": "integer"
        },
        "domainName": {
          "type": "string"
        },
        "domainPrefix": {
          "type": "string"
        },
        "protocol": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "RequestIdentity": {
      "type": "object",
      "properties": {
        "accessKey": {
          "type": "string"
        },
        "accountId": {
          "type": "string"
        },
        "apiKey": {
          "type": "string"
        },
        "caller": {
          "type": "string"
        },
        "cognitoIdentityId": {
          "type": "string"
        },
        "cognitoIdentityPoolId": {
          "type": "string"
        },
        "cognitoAuthenticationType": {
          "type": "string"
        },
        "cognitoAuthenticationProvider": {
          "type": "string"
        },
        "principalOrgId": {
          "type": "string"
        },
        "sourceIp": {
          "type": "string"
        },
        "user": {
          "type": "string"
        },
        "userAgent": {
          "type": "string"
        },
        "userArn": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  }
}

=== smirnoal/crema-lambda-runtime/events-schemas/src/test/resources/events/apigw-rest-sample.json
{
  "version": "1.0",
  "resource": "/my/path",
  "path": "/my/path",
  "httpMethod": "GET",
  "headers": {
    "Header1": "value1",
    "Header2": "value2"
  },
  "multiValueHeaders": {
    "Header1": [ "value1" ],
    "Header2": [ "value1", "value2" ]
  },
  "queryStringParameters": {
    "parameter1": "value1",
    "parameter2": "value"
  },
  "multiValueQueryStringParameters": {
    "parameter1": [ "value1", "value2" ],
    "parameter2": [ "value" ]
  },
  "requestContext": {
    "accountId": "123456789012",
    "apiId": "id",
    "domainName": "id.execute-api.us-east-1.amazonaws.com",
    "domainPrefix": "id",
    "httpMethod": "GET",
    "path": "/my/path",
    "protocol": "HTTP/1.1",
    "requestId": "id",
    "requestTime": "04/Mar/2020:19:15:17 +0000",
    "requestTimeEpoch": 1583349317135,
    "resourcePath": "/my/path",
    "stage": "$default"
  },
  "pathParameters": null,
  "stageVariables": null,
  "body": "Hello from Lambda!",
  "isBase64Encoded": false
}
