=== smirnoal/crema-lambda-runtime/events-schemas/src/main/resources/schemas/apigw-custom-authorizer.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "APIGatewayCustomAuthorizerEvent",
  "type": "object",
  "properties": {
    "version": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "methodArn": {
      "type": "string"
    },
    "identitySource": {
      "type": "string"
    },
    "authorizationToken": {
      "type": "string"
    },
    "resource": {
      "type": "string"
    },
    "path": {
      "type": "string"
    },
    "httpMethod": {
      "type": "string"
    },
    "headers": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "queryStringParameters": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "pathParameters": {
      "type": "object",
      "additionalProperties": true
    },
    "stageVariables": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "requestContext": {
      "type": "object",
      "additionalProperties": true
    }
  },
  "additionalProperties": false
}

=== smirnoal/crema-lambda-runtime/events-schemas/src/test/resources/events/apigw-custom-authorizer-sample.json
{
  "version": "1.0",
  "type": "REQUEST",
  "methodArn": "arn:aws:execute-api:us-east-1:123456789012:abcdef123/test/GET/request",
  "identitySource": "user1,123",
  "authorizationToken": "user1,123",
  "resource": "/request",
  "path": "/request",
  "httpMethod": "GET",
  "headers": {
    "X-AMZ-Date": "20170718T062915Z",
    "Accept": "*/*",
    "HeaderAuth1": "headerValue1",
    "CloudFront-Viewer-Country": "US",
    "CloudFront-Forwarded-Proto": "https",
    "CloudFront-Is-Tablet-Viewer": "false",
    "CloudFront-Is-Mobile-Viewer": "false",
    "User-Agent": "..."
  },
  "queryStringParameters": {
    "QueryString1": "queryValue1"
  },
  "pathParameters": { },
  "stageVariables": {
    "StageVar1": "stageValue1"
  },
  "requestContext": {
    "path": "/request",
    "accountId": "123456789012",
    "resourceId": "05c7jb",
    "stage": "test",
    "requestId": "...",
    "identity": {
      "apiKey": "...",
      "sourceIp": "..."
    },
    "resourcePath": "/request",
    "httpMethod": "GET",
    "apiId": "abcdef123"
  }
}
