=== smirnoal/crema-lambda-runtime/events-schemas/src/main/resources/schemas/cognito-event.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CognitoEvent",
  "type": "object",
  "properties": {
    "version": {
      "type": "integer"
    },
    "eventType": {
      "type": "string"
    },
    "region": {
      "type": "string"
    },
    "identityPoolId": {
      "type": "string"
    },
    "identityId": {
      "type": "string"
    },
    "datasetName": {
      "type": "string"
    },
    "datasetRecords": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/DatasetRecord"
      }
    }
  },
  "additionalProperties": false,
  "definitions": {
    "DatasetRecord": {
      "type": "object",
      "properties": {
        "oldValue": {
          "type": "string"
        },
        "newValue": {
          "type": "string"
        },
        "op": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  }
}

=== smirnoal/crema-lambda-runtime/events-schemas/src/test/resources/events/cognito-event-sample.json
{
  "version": 2,
  "eventType": "SyncTrigger",
  "region": "us-east-1",
  "identityPoolId": "identityPoolId",
  "identityId": "identityId",
  "datasetName": "datasetName",
  "datasetRecords": {
    "sampleKey1": {
      "oldValue": "oldValue1",
      "newValue": "newValue1",
      "op": "replace"
    },
    "sampleKey2": {
      "oldValue": "oldValue2",
      "newValue": "newValue2",
      "op": "replace"
    }
  }
}
