=== smirnoal/crema-lambda-runtime/events-schemas/src/main/resources/schemas/dynamodb-time-window.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "DynamodbTimeWindowEvent",
  "type": "object",
  "properties": {
    "Records": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": true
      }
    },
    "window": {
      "type": "object",
      "additionalProperties": true
    },
    "state": {
      "type": "object",
      "additionalProperties": true
    },
    "shardId": {
      "type": "string"
    },
    "eventSourceARN": {
      "type": "string"
    },
    "isFinalInvokeForWindow": {
      "type": "boolean"
    },
    "isWindowTerminatedEarly": {
      "type": "boolean"
    }
  },
  "additionalProperties": false
}

=== smirnoal/crema-lambda-runtime/events-schemas/src/test/resources/events/kinesis-time-window-event-sample.json
{
  "Records": [ {
    "kinesis": {
      "kinesisSchemaVersion": "1.0",
      "partitionKey": "1",
      "sequenceNumber": "49590338271490256608559692538361571095921575989136588898",
      "data": "SGVsbG8sIHRoaXMgaXMgYSB0ZXN0Lg==",
      "approximateArrivalTimestamp": 1.545084650987E9
    },
    "eventSource": "aws:kinesis",
    "eventVersion": "1.0",
    "eventID": "shardId-000000000006:49590338271490256608559692538361571095921575989136588898",
    "eventName": "aws:kinesis:record",
    "invokeIdentityArn": "arn:aws:iam::123456789012:role/lambda-kinesis-role",
    "awsRegion": "us-east-2",
    "eventSourceARN": "arn:aws:kinesis:us-east-2:123456789012:stream/lambda-stream"
  } ],
  "window": {
    "start": "2021-10-26T17:00:00Z",
    "end": "2021-10-26T17:05:00Z"
  },
  "state": {
    "1": "state1"
  },
  "shardId": "shardId-000000000006",
  "eventSourceARN": "arn:aws:kinesis:us-east-2:123456789012:stream/lambda-stream",
  "isFinalInvokeForWindow": false,
  "isWindowTerminatedEarly": false
}
