=== smirnoal/crema-lambda-runtime/events-schemas/src/main/resources/schemas/eventbridge.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "EventBridgeEvent",
  "type": "object",
  "properties": {
    "version": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "detail-type": {
      "type": "string"
    },
    "source": {
      "type": "string"
    },
    "account": {
      "type": "string"
    },
    "time": {
      "type": "string",
      "format": "date-time"
    },
    "region": {
      "type": "string"
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "detail": {
      "type": "object",
      "additionalProperties": true
    }
  },
  "additionalProperties": false
}

=== smirnoal/crema-lambda-runtime/events-schemas/src/test/resources/events/scheduled-sample.json
{
  "version": "0",
  "id": "fae0433b-7a0e-e383-7849-7e10153eaa47",
  "detail-type": "Scheduled Event",
  "source": "aws.events",
  "account": "123456789012",
  "time": "2020-09-30T15:58:34Z",
  "region": "eu-central-1",
  "resources": [ "arn:aws:events:eu-central-1:123456789012:rule/demoschedule" ],
  "detail": { }
}

=== smirnoal/crema-lambda-runtime/events-schemas/src/test/resources/events/eventbridge-sample.json
{
  "version": "0",
  "id": "fe8d3c65-xmpl-c5c3-2c87-81584709a377",
  "detail-type": "RDS DB Instance Event",
  "source": "aws.rds",
  "account": "123456789012",
  "time": "2020-04-28T07:20:20Z",
  "region": "us-east-2",
  "resources": [ "arn:aws:rds:us-east-2:123456789012:db:rdz6xmpliljlb1" ],
  "detail": {
    "EventCategories": [ "backup" ],
    "SourceType": "DB_INSTANCE",
    "SourceArn": "arn:aws:rds:us-east-2:123456789012:db:rdz6xmpliljlb1",
    "Date": "2020-04-28T07:20:20.112Z",
    "Message": "Finished DB Instance backup",
    "SourceIdentifier": "rdz6xmpliljlb1"
  }
}
