=== smirnoal/crema-lambda-runtime/events-schemas/src/main/resources/schemas/kafka.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "KafkaEvent",
  "type": "object",
  "properties": {
    "eventSource": {
      "type": "string"
    },
    "eventSourceArn": {
      "type": "string"
    },
    "bootstrapServers": {
      "type": "string"
    },
    "records": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": true
        }
      }
    }
  },
  "additionalProperties": false
}

=== smirnoal/crema-lambda-runtime/events-schemas/src/test/resources/events/kafka-event-sample.json
{
  "eventSource": "aws:kafka",
  "eventSourceArn": "arn:aws:kafka:us-west-2:012345678901:cluster/ExampleMSKCluster/e9f754c6-d29a-4430-a7db-958a19fd2c54-4",
  "bootstrapServers": "b-2.demo-cluster-1.a1bcde.c1.kafka.us-east-1.amazonaws.com:9092,b-1.demo-cluster-1.a1bcde.c1.kafka.us-east-1.amazonaws.com:9092",
  "records": {
    "AWSKafkaTopic-0": [ {
      "topic": "AWSKafkaTopic",
      "partition": 0,
      "offset": 0,
      "timestamp": 1595035749700,
      "timestampType": "CREATE_TIME",
      "key": "OGQ1NTk2YjQtMTgxMy00MjM4LWIyNGItNmRhZDhlM2QxYzBj",
      "value": "OGQ1NTk2YjQtMTgxMy00MjM4LWIyNGItNmRhZDhlM2QxYzBj",
      "headers": [ {
        "headerKey": "aGVhZGVyVmFsdWU="
      } ]
    } ]
  }
}
