=== smirnoal/crema-lambda-runtime/events-schemas/src/main/resources/schemas/kinesis-firehose.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "KinesisFirehoseEvent",
  "type": "object",
  "properties": {
    "invocationId": {
      "type": "string"
    },
    "deliveryStreamArn": {
      "type": "string"
    },
    "region": {
      "type": "string"
    },
    "records": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": true
      }
    }
  },
  "additionalProperties": false
}

=== smirnoal/crema-lambda-runtime/events-schemas/src/test/resources/events/kinesis-firehose-event-sample.json
{
  "invocationId": "invoked123",
  "deliveryStreamArn": "aws:lambda:events",
  "region": "us-west-2",
  "records": [ {
    "data": "SGVsbG8gV29ybGQ=",
    "recordId": "record1",
    "approximateArrivalEpoch": 1507217624302,
    "approximateArrivalTimestamp": 1507217624302,
    "kinesisRecordMetadata": {
      "shardId": "shardId-000000000000",
      "partitionKey": "4d1ad2b9-24f8-4b9d-a088-76e9947c317a",
      "approximateArrivalTimestamp": "1507217624302",
      "sequenceNumber": "49546986683135544286507457936321625675700192471156785154",
      "subsequenceNumber": ""
    }
  }, {
    "data": "SGVsbG8gV29ybGQ=",
    "recordId": "record2",
    "approximateArrivalEpoch": 1507217624302,
    "approximateArrivalTimestamp": 1507217624302,
    "kinesisRecordMetadata": {
      "shardId": "shardId-000000000001",
      "partitionKey": "4d1ad2b9-24f8-4b9d-a088-76e9947c318a",
      "approximateArrivalTimestamp": "1507217624302",
      "sequenceNumber": "49546986683135544286507457936321625675700192471156785155",
      "subsequenceNumber": ""
    }
  } ]
}
