=== smirnoal/crema-lambda-runtime/events-schemas/src/main/resources/schemas/kinesis-analytics-streams-input-preprocessing.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "KinesisAnalyticsStreamsInputPreprocessingEvent",
  "type": "object",
  "properties": {
    "invocationId": {
      "type": "string"
    },
    "applicationArn": {
      "type": "string"
    },
    "streamArn": {
      "type": "string"
    },
    "records": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": true
      }
    }
  },
  "additionalProperties": false
}

=== smirnoal/crema-lambda-runtime/events-schemas/src/test/resources/events/kinesis-analytics-firehose-input-preprocessing-event-sample.json
{
  "invocationId": "00540a87-5050-496a-84e4-e7d92bbaf5e2",
  "applicationArn": "arn:aws:kinesisanalytics:us-east-1:12345678911:application/lambda-test",
  "streamArn": "arn:aws:firehose:us-east-1:AAAAAAAAAAAA:deliverystream/lambda-test",
  "records": [ {
    "recordId": "49572672223665514422805246926656954630972486059535892482",
    "data": "aGVsbG8gd29ybGQ=",
    "kinesisFirehoseRecordMetadata": {
      "approximateArrivalTimestamp": 1520280173
    }
  } ]
}
