=== smirnoal/crema-lambda-runtime/events-schemas/src/main/resources/schemas/lexv2-event.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "LexV2Event",
  "type": "object",
  "properties": {
    "sessionId": {
      "type": "string"
    },
    "inputTranscript": {
      "type": "string"
    },
    "interpretations": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": true
      }
    },
    "responseContentType": {
      "type": "string"
    },
    "invocationSource": {
      "type": "string"
    },
    "messageVersion": {
      "type": "string"
    },
    "sessionState": {
      "type": "object",
      "additionalProperties": true
    },
    "inputMode": {
      "type": "string"
    },
    "bot": {
      "type": "object",
      "additionalProperties": true
    }
  },
  "additionalProperties": false
}

=== smirnoal/crema-lambda-runtime/events-schemas/src/test/resources/events/lexv2-event-sample.json
{
  "sessionId": "123456789123456",
  "inputTranscript": "deluxe",
  "interpretations": [ {
    "intent": {
      "slots": {
        "RoomType": {
          "shape": "Scalar",
          "value": {
            "originalValue": "deluxe",
            "resolvedValues": [ "deluxe" ],
            "interpretedValue": "deluxe"
          }
        },
        "CheckInDate": {
          "shape": "Scalar",
          "value": {
            "originalValue": "fifth of may",
            "resolvedValues": [ "2022-05-05" ],
            "interpretedValue": "2022-05-05"
          }
        },
        "Nights": {
          "shape": "Scalar",
          "value": {
            "originalValue": "fourteen",
            "resolvedValues": [ "14" ],
            "interpretedValue": "14"
          }
        },
        "Location": {
          "shape": "Scalar",
          "value": {
            "originalValue": "seattle",
            "resolvedValues": [ "seattle" ],
            "interpretedValue": "seattle"
          }
        }
      },
      "confirmationState": "None",
      "name": "BookHotel",
      "state": "InProgress"
    },
    "nluConfidence": 1
  }, {
    "intent": {
      "slots": { },
      "confirmationState": "None",
      "name": "FallbackIntent",
      "state": "InProgress"
    }
  }, {
    "intent": {
      "slots": {
        "ReturnDate": null,
        "PickUpDate": null,
        "DriverAge": null,
        "CarType": null,
        "PickUpCity": null
      },
      "confirmationState": "None",
      "name": "BookCar",
      "state": "InProgress"
    },
    "nluConfidence": 0.52
  } ],
  "responseContentType": "text/plain; charset=utf-8",
  "invocationSource": "DialogCodeHook",
  "messageVersion": "1.0",
  "sessionState": {
    "originatingRequestId": "00000000-1111-2222-3333-444444444444",
    "activeContexts": [ ],
    "intent": {
      "slots": {
        "RoomType": {
          "shape": "Scalar",
          "value": {
            "originalValue": "deluxe",
            "resolvedValues": [ "deluxe" ],
            "interpretedValue": "deluxe"
          }
        },
        "CheckInDate": {
          "shape": "Scalar",
          "value": {
            "originalValue": "fifth of may",
            "resolvedValues": [ "2022-05-05" ],
            "interpretedValue": "2022-05-05"
          }
        },
        "Nights": {
          "shape": "Scalar",
          "value": {
            "originalValue": "fourteen",
            "resolvedValues": [ "14" ],
            "interpretedValue": "14"
          }
        },
        "Location": {
          "shape": "Scalar",
          "value": {
            "originalValue": "seattle",
            "resolvedValues": [ "seattle" ],
            "interpretedValue": "seattle"
          }
        }
      },
      "confirmationState": "None",
      "name": "BookHotel",
      "state": "InProgress"
    }
  },
  "inputMode": "Text",
  "bot": {
    "aliasName": "TestBotAlias",
    "aliasId": "TSTALIASID",
    "name": "BookTrip",
    "version": "DRAFT",
    "localeId": "en_US",
    "id": "ABCDE01235"
  }
}
